spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: bankOne
    password: bankOne

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
app:
  description: Dev version of bank app
  server:
    stage: dev